version: 0.2
phases:
  pre_build:
    commands:
      - cd BillingDataInfrastructure
     
  post_build:
    commands:
      - echo Test started on `date`
      - aws cloudformation validate-template --template-body file://BillingData.template